version: '3.9'

services:
  frontend: # Name of our service
    build: ./frontend # path to dockerfile
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    links:
      - backend

  backend:
    build: ./backend
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    container_name: backend-docker
    depends_on:
      - mongodb
    restart: always
    env_file: ./.env
    stdin_open: true
    tty: true

# open mongo cli - docker-compose exec mongodb mongo
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
volumes:
  db: